[core]
plugins = \
  autostart \
  move \
  place \
  ipc \
  ipc-rules \
  wm-actions \
  window-rules \
  resize

[autostart]
screensaver = false
dpms = false
# RB-01 Interface
kiosk = /home/pi/display.sh
# Enable the waydroind integration
#android = /home/pi/android/waydroid.sh
# RB-Avionics native task manager with recovery interface
#rb = /home/pi/android/rb-taskmanager.sh

[window-rules]
#rulerba = on created if app_id contains "chrom" then set geometry 0 100 480 480
#rulerbb = on created if app_id contains "chrom" then set geometry 0 100 480 480